---
- name: Update and upgrade apt packages
  become: true
  hosts: all
  tasks:
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes

    - name: Upgrade packages to the latest version
      apt:
        upgrade: dist