---
- name: Update and upgrade apt packages
  hosts: all
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade packages to the latest version
      become: true
      apt:
        upgrade: dist